pipeline {
    agent any

    tools {
        maven 'maven'
    }

    stages {
        stage('Pull') {
            steps {
                git url: "https://github.com/AaronDownward/Challenge-1", branch: "test"
            }
        }
        stage('Test') {
            steps {
                sh "mvn test -Dcheckstyle.skip=true"
            }
        }
        stage('Build') {
            steps {
                sh 'ls'
                sh "mvn package -DskipTests=true -Dcheckstyle.skip=true"
            }
        }

        stage('Upload Docker Image') {
            steps {
                script {
                    docker.withTool('docker') {
                        repoId = "aarondownward/simple-app"
                        image = docker.build(repoId)
                        docker.withRegistry("https://registry.hub.docker.com", "dockerhub-cred") {
                            image.push()
                        }
                    }
                }
            }
        }
        stage('Deploy to Testing') {
            steps {
                withKubeConfig([credentialsId: 'kubectl-creds', serverUrl: 'https://7B7243814A301887F34329CEF514F6CC.gr7.us-east-2.eks.amazonaws.com']) {
                    sh 'ls'
                    sh 'kubectl apply -f kube-deployments/testing/deployment.yaml'
                    sh 'kubectl apply -f kube-deployments/testing/service.yaml'
                    sh 'kubectl rollout restart deployment/simple-app -n testing'
                }
            }
        }
    }
}
